version: '3'

services:

  storage.minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./volumes/storages/minio:/data
    env_file:
      - .env
    command: server --console-address :9009 /data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pv121_java

  mongoDb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/mongodb:/data/db
    environment:
      SERVER_NAME: java.db.mongodb
    env_file:
      - .env
    networks:
      - pv121_java
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  redis:
    image: 'redis'
    volumes:
      - './volumes/redis:/data'
    ports:
      - '6379:6379'
    networks:
      - pv121_java
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  java.db.mysql:
    image: mysql:8.0.34
    environment:
      SERVER_NAME: java.db.mysql
    env_file:
      - .env
    ports:
      - "30121:3306"
    volumes:
      - ./volumes/java.db.mysql:/var/lib/mysql
    networks:
      - pv121_java
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  pma:
    image: phpmyadmin
    ports:
      - "30122:80"
    environment:
      PMA_HOST: java.db.mysql
      PMA_PORT: 3306

    networks:
      - pv121_java
    extra_hosts:
      - 'host.docker.internal:host-gateway'


networks:
  pv121_java:
    driver: bridge